#!/usr/bin/env npx tsx

/**
 * Rebuild data/sources/youtube-channels.json from the starter file
 * plus a curated long-form / podcast pack. Metadata only.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

interface Channel {
  id: string;
  handle: string;
  title: string;
  language: string;
  creators: string[];
  description: string;
  tags: string[];
  genres: string[];
  region: string;
  country: string;
  countryCode: string;
  youtube: string;
  website?: string;
  english?: { title: string; description: string };
}

type Row = [
  handle: string,
  title: string,
  language: string,
  creators: string,
  description: string,
  tags: string,
  genres: string,
  countryCode: string,
];

const PLACE: Record<string, [string, string, string]> = {
  US: ['north-america', 'United States', 'US'],
  GB: ['uk-ireland', 'United Kingdom', 'GB'],
  CA: ['north-america', 'Canada', 'CA'],
  AU: ['oceania', 'Australia', 'AU'],
  NZ: ['oceania', 'New Zealand', 'NZ'],
  IE: ['uk-ireland', 'Ireland', 'IE'],
  ES: ['iberia', 'Spain', 'ES'],
  MX: ['latin-america', 'Mexico', 'MX'],
  AR: ['latin-america', 'Argentina', 'AR'],
  CL: ['latin-america', 'Chile', 'CL'],
  CO: ['latin-america', 'Colombia', 'CO'],
  PE: ['andes', 'Peru', 'PE'],
  EC: ['andes', 'Ecuador', 'EC'],
  UY: ['latin-america', 'Uruguay', 'UY'],
  VE: ['latin-america', 'Venezuela', 'VE'],
  GT: ['mesoamerica', 'Guatemala', 'GT'],
  CR: ['mesoamerica', 'Costa Rica', 'CR'],
  BR: ['latin-america', 'Brazil', 'BR'],
  FR: ['western-europe', 'France', 'FR'],
  DE: ['central-europe', 'Germany', 'DE'],
  IT: ['southern-europe', 'Italy', 'IT'],
  PT: ['iberia', 'Portugal', 'PT'],
  NL: ['western-europe', 'Netherlands', 'NL'],
  SE: ['nordic', 'Sweden', 'SE'],
  NO: ['nordic', 'Norway', 'NO'],
  DK: ['nordic', 'Denmark', 'DK'],
  FI: ['nordic', 'Finland', 'FI'],
  PL: ['central-europe', 'Poland', 'PL'],
  IN: ['india', 'India', 'IN'],
  JP: ['east-asia', 'Japan', 'JP'],
  KR: ['east-asia', 'South Korea', 'KR'],
  TW: ['east-asia', 'Taiwan', 'TW'],
  CN: ['east-asia', 'China', 'CN'],
  ID: ['southeast-asia', 'Indonesia', 'ID'],
  VN: ['southeast-asia', 'Vietnam', 'VN'],
  TH: ['southeast-asia', 'Thailand', 'TH'],
  PH: ['southeast-asia', 'Philippines', 'PH'],
  NG: ['west-africa', 'Nigeria', 'NG'],
  ZA: ['southern-africa', 'South Africa', 'ZA'],
  KE: ['east-africa', 'Kenya', 'KE'],
  EG: ['arabia', 'Egypt', 'EG'],
  QA: ['arabia', 'Qatar', 'QA'],
  AE: ['arabia', 'United Arab Emirates', 'AE'],
  CH: ['western-europe', 'Switzerland', 'CH'],
  LV: ['eastern-europe', 'Latvia', 'LV'],
  HK: ['east-asia', 'Hong Kong', 'HK'],
  SG: ['southeast-asia', 'Singapore', 'SG'],
  IL: ['levant', 'Israel', 'IL'],
  TR: ['western-europe', 'Turkey', 'TR'],
  UA: ['eastern-europe', 'Ukraine', 'UA'],
  HU: ['central-europe', 'Hungary', 'HU'],
  RO: ['eastern-europe', 'Romania', 'RO'],
};

function expand(rows: Row[]): Channel[] {
  return rows.map((row) => {
    const [handle, title, language, creators, description, tags, genres, cc] =
      row;
    const place = PLACE[cc] ?? ['north-america', 'Unknown', cc];
    const id = `yt-${handle
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')}`;
    return {
      id,
      handle,
      title,
      language,
      creators: creators.split('|').map((name) => name.trim()),
      description,
      tags: tags.split(',').map((tag) => tag.trim()),
      genres: genres.split(',').map((genre) => genre.trim()),
      region: place[0],
      country: place[1],
      countryCode: cc,
      youtube: `https://www.youtube.com/@${handle}`,
    };
  });
}

/** Compact rows: handle, title, lang, creators, desc, tags, genres, countryCode */
const PACK: Row[] = [
  // Seed-aligned mirrors and peers
  [
    'nathagens',
    'Nate Hagens',
    'en',
    'Nate Hagens',
    'Energy, ecology, and the economic transition — the YouTube home of The Great Simplification.',
    'energy,ecology,nate-hagens,interview,longform',
    'science,society-culture',
    'US',
  ],
  [
    'planetcritical',
    'Planet: Critical',
    'en',
    'Rachel Donald',
    'Rachel Donald’s climate and political interviews on video.',
    'climate,ecology,rachel-donald,politics,interview',
    'news,society-culture',
    'GB',
  ],
  [
    'democracynow',
    'Democracy Now!',
    'en',
    'Amy Goodman|Juan González',
    'Independent daily news hour. Pacifica-born; long segments, not shorts.',
    'pacifica,public-radio,news,interview',
    'news,current-affairs',
    'US',
  ],
  [
    'kpfk907fm',
    'KPFK 90.7 FM',
    'en',
    'KPFK',
    'Los Angeles Pacifica station: talks, ecojustice, and evening news on video.',
    'pacifica,kpfk,public-radio,ecojustice',
    'news,society-culture',
    'US',
  ],
  [
    'kpfa',
    'KPFA',
    'en',
    'KPFA',
    'Berkeley Pacifica: Against the Grain and other long public-radio hours.',
    'pacifica,kpfa,public-radio',
    'news,society-culture',
    'US',
  ],
  [
    'wbai',
    'WBAI',
    'en',
    'WBAI',
    'New York Pacifica desk on video.',
    'pacifica,wbai,public-radio',
    'news,current-affairs',
    'US',
  ],
  [
    'radioambulante',
    'Radio Ambulante',
    'es',
    'Radio Ambulante Estudios',
    'Crónicas latinoamericanas en video: el podcast, también en YouTube.',
    'crónica,latam,interview,spanish,longform',
    'journalism,storytelling',
    'US',
  ],
  [
    'elhilo',
    'El hilo',
    'es',
    'Radio Ambulante Estudios',
    'Noticias de América Latina con contexto, en video.',
    'news,latam,spanish,context',
    'news,current-affairs',
    'US',
  ],
  [
    'mongabay',
    'Mongabay',
    'en',
    'Mongabay',
    'Conservation journalism: forests, wildlife, and climate reporting.',
    'climate,ecology,conservation,journalism',
    'news,science',
    'US',
  ],
  [
    'mongabaylatam',
    'Mongabay Latam',
    'es',
    'Mongabay Latam',
    'Periodismo ambiental en español: Amazonía, Andes y océanos.',
    'ecology,andes,amazon,spanish,climate',
    'news,science',
    'PE',
  ],
  [
    'justhaveathink',
    'Just Have a Think',
    'en',
    'Dave Borlace',
    'Climate and energy explainers that sit with the numbers.',
    'climate,energy,ecology,explainer',
    'science,education',
    'GB',
  ],
  [
    'ourchangingclimate',
    'Our Changing Climate',
    'en',
    'Our Changing Climate',
    'Essays on climate, capitalism, and the living world.',
    'climate,ecology,politics,essay',
    'ideas,science',
    'US',
  ],
  [
    'ClimateTown',
    'Climate Town',
    'en',
    'Rollie Williams',
    'Climate comedy that still cites the report.',
    'climate,comedy,explainer',
    'education,science',
    'US',
  ],
  [
    '350org',
    '350.org',
    'en',
    '350.org',
    'Climate organising talks and briefings.',
    'climate,ecojustice,organizing',
    'news,society-culture',
    'US',
  ],
  [
    'carbonbrief',
    'Carbon Brief',
    'en',
    'Carbon Brief',
    'UK climate science and policy, unpacked at length.',
    'climate,energy,science,policy',
    'news,science',
    'GB',
  ],
  [
    'yaleclimateconnections',
    'Yale Climate Connections',
    'en',
    'Yale Climate Connections',
    'Short and long climate stories from a university desk.',
    'climate,science,journalism',
    'news,science',
    'US',
  ],
  [
    'drillednews',
    'Drilled',
    'en',
    'Amy Westervelt',
    'Investigations into fossil PR and climate delay.',
    'climate,journalism,energy',
    'news,society-culture',
    'US',
  ],
  [
    'startalk',
    'StarTalk',
    'en',
    'Neil deGrasse Tyson',
    'Science interviews and cosmic Q&A — a peer to 632nm-style conversations.',
    'science,interviews,research,longform',
    'science,ideas',
    'US',
  ],
  [
    'seancarroll',
    'Sean Carroll',
    'en',
    'Sean Carroll',
    'Mindscape: physicists, philosophers, and patient interviews.',
    'science,interviews,research,longform',
    'science,ideas',
    'US',
  ],
  [
    'hubermanlab',
    'Huberman Lab',
    'en',
    'Andrew Huberman',
    'Long health-science briefings and guest conversations.',
    'science,interviews,health,longform',
    'science,education',
    'US',
  ],
  [
    'theroyalinstitution',
    'The Royal Institution',
    'en',
    'The Royal Institution',
    'Full-length science lectures from the Faraday theatre.',
    'science,lecture,research,longform',
    'science,education',
    'GB',
  ],
  [
    'longnow',
    'The Long Now Foundation',
    'en',
    'The Long Now Foundation',
    'Seminars about long-term thinking, energy, and civilisation.',
    'ideas,energy,longform,lecture',
    'ideas,science',
    'US',
  ],
  [
    '80000Hours',
    '80,000 Hours',
    'en',
    '80,000 Hours',
    'Long interviews on doing good with a career.',
    'interview,longform,ideas',
    'ideas,society-culture',
    'GB',
  ],
  [
    'futureoflifeinstitute',
    'Future of Life Institute',
    'en',
    'Future of Life Institute',
    'Talks on AI, biotech, and existential risk.',
    'science,ai,interview,research',
    'science,ideas',
    'US',
  ],
  [
    'redsemillas',
    'Red de Guardianes de Semillas',
    'es',
    'Red de Guardianes de Semillas',
    'Agroecología andina en video — el entorno de Radio Semilla.',
    'seeds,agroecology,andes,semillas,spanish',
    'society-culture,science',
    'EC',
  ],
  [
    'accionecologica',
    'Acción Ecológica',
    'es',
    'Acción Ecológica',
    'Ecología política desde Ecuador.',
    'ecology,andes,climate,spanish',
    'news,society-culture',
    'EC',
  ],

  // English science / interview / long-form talk
  [
    'DwarkeshPatel',
    'Dwarkesh Patel',
    'en',
    'Dwarkesh Patel',
    'Patient interviews with researchers and builders.',
    'interview,ai,longform,science',
    'ideas,science',
    'US',
  ],
  [
    'veritasium',
    'Veritasium',
    'en',
    'Derek Muller',
    'Science films that start with a wrong intuition.',
    'science,education,physics',
    'education,science',
    'AU',
  ],
  [
    'vsauce',
    'Vsauce',
    'en',
    'Michael Stevens',
    'Long curiosity essays that wander into research.',
    'science,education,longform',
    'education,science',
    'US',
  ],
  [
    '3blue1brown',
    '3Blue1Brown',
    'en',
    'Grant Sanderson',
    'Long visual maths lectures.',
    'science,maths,lecture',
    'education,science',
    'US',
  ],
  [
    'numberphile',
    'Numberphile',
    'en',
    'Brady Haran',
    'Mathematicians talking, not racing.',
    'science,maths,interview',
    'education,science',
    'GB',
  ],
  [
    'computerphile',
    'Computerphile',
    'en',
    'Brady Haran',
    'Computer scientists at a table.',
    'science,computing,interview',
    'education,science',
    'GB',
  ],
  [
    'sixtysymbols',
    'Sixty Symbols',
    'en',
    'Brady Haran',
    'Physicists explaining one symbol at a time.',
    'science,physics,interview',
    'education,science',
    'GB',
  ],
  [
    'periodicvideos',
    'Periodic Videos',
    'en',
    'Brady Haran',
    'Chemistry conversations from Nottingham.',
    'science,chemistry,interview',
    'education,science',
    'GB',
  ],
  [
    'pbsspacetime',
    'PBS Space Time',
    'en',
    'Matt O’Dowd',
    'Cosmology lectures that assume you will stay.',
    'science,physics,lecture',
    'education,science',
    'US',
  ],
  [
    'CoolWorldsLab',
    'Cool Worlds',
    'en',
    'David Kipping',
    'Columbia exoplanet talks and interviews.',
    'science,astronomy,research,interview',
    'science,education',
    'US',
  ],
  [
    'whatdamath',
    'Anton Petrov',
    'en',
    'Anton Petrov',
    'Daily space and science briefings with sources.',
    'science,astronomy,research',
    'science,education',
    'US',
  ],
  [
    'frasercain',
    'Fraser Cain',
    'en',
    'Fraser Cain',
    'Universe Today Q&A — long astronomy conversations.',
    'science,astronomy,interview',
    'science,education',
    'CA',
  ],
  [
    'eventhorizonshow',
    'Event Horizon',
    'en',
    'John Michael Godier',
    'Long interviews on space, physics, and SETI.',
    'science,interviews,research,longform',
    'science,ideas',
    'US',
  ],
  [
    'TheJoyofWhy',
    'The Joy of Why',
    'en',
    'Quanta Magazine',
    'Quanta’s interview series on maths and science.',
    'science,interviews,research',
    'science,ideas',
    'US',
  ],
  [
    'QuantaScienceChannel',
    'Quanta Magazine',
    'en',
    'Quanta Magazine',
    'Longer science stories from the Simons desk.',
    'science,research,journalism',
    'science,education',
    'US',
  ],
  [
    'naturevideo',
    'Nature Video',
    'en',
    'Nature',
    'Research films and scientist conversations.',
    'science,research,journalism',
    'science,education',
    'GB',
  ],
  [
    'ScienceMagazine',
    'Science Magazine',
    'en',
    'Science',
    'AAAS talks and paper conversations.',
    'science,research,journalism',
    'science,education',
    'US',
  ],
  [
    'TED',
    'TED',
    'en',
    'TED',
    'Talks that still last longer than a short.',
    'lecture,ideas,interview',
    'ideas,education',
    'US',
  ],
  [
    'TEDEd',
    'TED-Ed',
    'en',
    'TED-Ed',
    'Lessons and longer explainers.',
    'education,explainer,science',
    'education,science',
    'US',
  ],
  [
    'bigthink',
    'Big Think',
    'en',
    'Big Think',
    'Expert interviews on science, philosophy, and policy.',
    'interview,ideas,science,longform',
    'ideas,education',
    'US',
  ],
  [
    'Intelligence2',
    'Intelligence Squared',
    'en',
    'Intelligence Squared',
    'Full Oxford-style debates and interviews.',
    'debate,interview,ideas,longform',
    'ideas,current-affairs',
    'GB',
  ],
  [
    'howtoacademy',
    'How To Academy',
    'en',
    'How To Academy',
    'London live interviews with writers and scientists.',
    'interview,ideas,longform',
    'ideas,culture',
    'GB',
  ],
  [
    'theRSAorg',
    'RSA',
    'en',
    'RSA',
    'RSA talks: ideas, climate, and the commons.',
    'lecture,ideas,climate,longform',
    'ideas,society-culture',
    'GB',
  ],
  [
    'ChathamHouse',
    'Chatham House',
    'en',
    'Chatham House',
    'International-affairs conversations.',
    'interview,geopolitics,policy',
    'current-affairs,ideas',
    'GB',
  ],
  [
    'CFR_org',
    'Council on Foreign Relations',
    'en',
    'CFR',
    'Foreign-policy interviews and panels.',
    'interview,geopolitics,policy',
    'current-affairs,ideas',
    'US',
  ],
  [
    'BrookingsInst',
    'Brookings Institution',
    'en',
    'Brookings',
    'Policy panels that run the hour.',
    'policy,interview,lecture',
    'current-affairs,ideas',
    'US',
  ],
  [
    'csis',
    'CSIS',
    'en',
    'CSIS',
    'Washington security and geopolitics talks.',
    'geopolitics,interview,policy',
    'current-affairs,ideas',
    'US',
  ],
  [
    'CarnegieEndowment',
    'Carnegie Endowment',
    'en',
    'Carnegie Endowment',
    'International-affairs conversations.',
    'geopolitics,interview,policy',
    'current-affairs,ideas',
    'US',
  ],
  [
    'OxfordUnion',
    'Oxford Union',
    'en',
    'Oxford Union',
    'Full addresses and questions.',
    'lecture,debate,interview,longform',
    'ideas,culture',
    'GB',
  ],
  [
    'cambridgeunion',
    'Cambridge Union',
    'en',
    'Cambridge Union',
    'Cambridge debates and guest hours.',
    'lecture,debate,interview,longform',
    'ideas,culture',
    'GB',
  ],
  [
    'theori',
    'The ORI',
    'en',
    'Oxford Research',
    'Research conversations (when posted as talks).',
    'science,lecture,research',
    'science,education',
    'GB',
  ],
  [
    'mitocw',
    'MIT OpenCourseWare',
    'en',
    'MIT',
    'Full lecture series. A spoken archive.',
    'lecture,science,education,longform',
    'education,science',
    'US',
  ],
  [
    'stanford',
    'Stanford',
    'en',
    'Stanford',
    'University talks and interview series.',
    'lecture,interview,education',
    'education,ideas',
    'US',
  ],
  [
    'Harvard',
    'Harvard University',
    'en',
    'Harvard',
    'Lectures and Institute talks.',
    'lecture,education,ideas',
    'education,ideas',
    'US',
  ],
  [
    'YCombinator',
    'Y Combinator',
    'en',
    'Y Combinator',
    'Startup interviews that still take an hour.',
    'interview,business,longform',
    'business,ideas',
    'US',
  ],
  [
    'a16z',
    'a16z',
    'en',
    'Andreessen Horowitz',
    'Tech and culture conversations.',
    'interview,tech,longform',
    'business,ideas',
    'US',
  ],
  [
    'twimlai',
    'This Week in Machine Learning & AI',
    'en',
    'Sam Charrington',
    'ML interviews with researchers.',
    'ai,science,interviews,research',
    'science,ideas',
    'US',
  ],
  [
    'MachineLearningStreetTalk',
    'Machine Learning Street Talk',
    'en',
    'MLST',
    'Unhurried technical interviews.',
    'ai,science,interviews,research,longform',
    'science,ideas',
    'GB',
  ],
  [
    'yannickilcher',
    'Yannic Kilcher',
    'en',
    'Yannic Kilcher',
    'Paper talks and ML conversations.',
    'ai,science,research,interview',
    'science,education',
    'CH',
  ],
  [
    'TwoMinutePapers',
    'Two Minute Papers',
    'en',
    'Károly Zsolnai-Fehér',
    'Research papers, sometimes at length.',
    'science,ai,research',
    'science,education',
    'HU',
  ],
  [
    'PracticalAI',
    'Practical AI',
    'en',
    'Changelog',
    'Applied-AI conversations.',
    'ai,interview,tech',
    'science,business',
    'US',
  ],
  [
    'datascience',
    'Data Skeptic',
    'en',
    'Kyle Polich',
    'Skeptical data-science interviews.',
    'science,interviews,research',
    'science,education',
    'US',
  ],
  [
    'lexiclips',
    'Lex Fridman Clips',
    'en',
    'Lex Fridman',
    'Clips from the long interviews — still conversation-first.',
    'interview,ai,longform,science',
    'ideas,science',
    'US',
  ],
  [
    'PowerfulJRE',
    'PowerfulJRE',
    'en',
    'Joe Rogan',
    'Full Joe Rogan Experience uploads when they appear.',
    'interview,conversation,longform',
    'society-culture,ideas',
    'US',
  ],
  [
    'joerogan',
    'Joe Rogan',
    'en',
    'Joe Rogan',
    'The host channel for long conversations.',
    'interview,conversation,longform',
    'society-culture,ideas',
    'US',
  ],
  [
    'chrischristopherwilliamson',
    'Modern Wisdom',
    'en',
    'Chris Williamson',
    'Long interviews on culture, science, and sport.',
    'interview,conversation,longform',
    'society-culture,ideas',
    'GB',
  ],
  [
    'TheDiaryOfACEO',
    'The Diary Of A CEO',
    'en',
    'Steven Bartlett',
    'Long founder and culture interviews.',
    'interview,business,longform',
    'business,society-culture',
    'GB',
  ],
  [
    'timferriss',
    'Tim Ferriss',
    'en',
    'Tim Ferriss',
    'The Tim Ferriss Show on video.',
    'interview,longform,conversation',
    'ideas,business',
    'US',
  ],
  [
    'samharrisorg',
    'Sam Harris',
    'en',
    'Sam Harris',
    'Making Sense conversations.',
    'interview,ideas,longform,conversation',
    'ideas,society-culture',
    'US',
  ],
  [
    'jordanbpeterson',
    'Jordan B Peterson',
    'en',
    'Jordan B. Peterson',
    'Long lectures and interviews.',
    'interview,lecture,longform,conversation',
    'ideas,society-culture',
    'CA',
  ],
  [
    'triggerpod',
    'Triggernometry',
    'en',
    'Konstantin Kisin|Francis Foster',
    'Long political and culture interviews from London.',
    'interview,politics,longform,conversation',
    'current-affairs,ideas',
    'GB',
  ],
  [
    'econlib',
    'EconTalk',
    'en',
    'Russ Roberts',
    'Economics conversations that take the hour.',
    'interview,economics,longform',
    'ideas,business',
    'US',
  ],
  [
    'MercatusCenter',
    'Conversations with Tyler',
    'en',
    'Tyler Cowen',
    'Eclectic long interviews.',
    'interview,ideas,longform,conversation',
    'ideas,culture',
    'US',
  ],
  [
    'acquiredfm',
    'Acquired',
    'en',
    'Ben Gilbert|David Rosenthal',
    'Company histories told as long conversations.',
    'interview,business,longform',
    'business,history',
    'US',
  ],
  [
    'InvestLikeTheBest',
    'Invest Like the Best',
    'en',
    'Patrick O’Shaughnessy',
    'Investor interviews.',
    'interview,business,longform',
    'business,ideas',
    'US',
  ],
  [
    'TheKnowledgeProject',
    'The Knowledge Project',
    'en',
    'Shane Parrish',
    'Farnam Street interviews.',
    'interview,ideas,longform',
    'ideas,business',
    'CA',
  ],
  [
    'allin',
    'All-In Podcast',
    'en',
    'All-In',
    'Four hosts, one long tech-politics conversation.',
    'interview,tech,politics,longform',
    'business,current-affairs',
    'US',
  ],
  [
    'pivot',
    'Pivot',
    'en',
    'Kara Swisher|Scott Galloway',
    'Tech and media conversations.',
    'interview,tech,business',
    'business,current-affairs',
    'US',
  ],
  [
    'hardfork',
    'Hard Fork',
    'en',
    'Kevin Roose|Casey Newton',
    'NYT tech conversations on video.',
    'interview,tech,longform',
    'business,current-affairs',
    'US',
  ],
  [
    'theverge',
    'The Verge',
    'en',
    'The Verge',
    'Decoder and Vergecast hours.',
    'interview,tech,longform',
    'business,current-affairs',
    'US',
  ],
  [
    'darknetdiaries',
    'Darknet Diaries',
    'en',
    'Jack Rhysider',
    'True hacking stories as long narration.',
    'security,storytelling,longform',
    'journalism,technology',
    'US',
  ],
  [
    'twit',
    'TWiT',
    'en',
    'Leo Laporte',
    'This Week in Tech and sister shows.',
    'tech,interview,longform',
    'technology,current-affairs',
    'US',
  ],
  [
    'securitynow',
    'Security Now',
    'en',
    'Steve Gibson|Leo Laporte',
    'Weekly security conversations.',
    'security,tech,interview',
    'technology,education',
    'US',
  ],
  [
    'hiddenbrain',
    'Hidden Brain',
    'en',
    'Shankar Vedantam',
    'Social-science stories and interviews.',
    'science,interview,storytelling',
    'ideas,science',
    'US',
  ],
  [
    'radiolab',
    'Radiolab',
    'en',
    'WNYC Studios',
    'Sound-rich science and story hours.',
    'science,storytelling,public-radio,longform',
    'storytelling,science',
    'US',
  ],
  [
    'thisamericanlife',
    'This American Life',
    'en',
    'Ira Glass',
    'The radio magazine on video when episodes are posted.',
    'storytelling,public-radio,longform',
    'storytelling,journalism',
    'US',
  ],
  [
    '99pi',
    '99% Invisible',
    'en',
    'Roman Mars',
    'Design and city stories.',
    'design,storytelling,interview',
    'culture,education',
    'US',
  ],
  [
    'ezrakleinshow',
    'The Ezra Klein Show',
    'en',
    'Ezra Klein',
    'Long political and ideas interviews.',
    'interview,politics,ideas,longform',
    'ideas,current-affairs',
    'US',
  ],
  [
    'nytimes',
    'The New York Times',
    'en',
    'The New York Times',
    'The Daily and longer Times conversations.',
    'news,interview,journalism',
    'news,current-affairs',
    'US',
  ],
  [
    'npr',
    'NPR',
    'en',
    'NPR',
    'Public-radio hours: Fresh Air, Throughline, Planet Money.',
    'public-radio,interview,news,longform',
    'news,culture',
    'US',
  ],
  [
    'freshair',
    'Fresh Air',
    'en',
    'Terry Gross|WHYY',
    'The interview hour.',
    'interview,public-radio,conversation,longform',
    'culture,journalism',
    'US',
  ],
  [
    'onbeing',
    'On Being',
    'en',
    'Krista Tippett',
    'Spiritual and civic conversations.',
    'interview,conversation,longform,ideas',
    'ideas,culture',
    'US',
  ],
  [
    'wnycstudios',
    'WNYC Studios',
    'en',
    'WNYC Studios',
    'New York public-radio shows on video.',
    'public-radio,interview,storytelling',
    'culture,journalism',
    'US',
  ],
  [
    'pbs',
    'PBS',
    'en',
    'PBS',
    'Frontline, Amanpour, and long interviews.',
    'documentary,interview,public-media',
    'news,documentary',
    'US',
  ],
  [
    'frontlinepbs',
    'FRONTLINE PBS',
    'en',
    'FRONTLINE',
    'Long investigations.',
    'documentary,journalism,investigation',
    'documentary,news',
    'US',
  ],
  [
    'AmanpourandCompany',
    'Amanpour and Company',
    'en',
    'Christiane Amanpour',
    'Global interview hour.',
    'interview,news,longform',
    'news,current-affairs',
    'US',
  ],
  [
    'CBSSundayMorning',
    'CBS Sunday Morning',
    'en',
    'CBS',
    'Longer network features.',
    'journalism,culture,interview',
    'culture,news',
    'US',
  ],
  [
    '60minutes',
    '60 Minutes',
    'en',
    '60 Minutes',
    'Long-form network interviews.',
    'journalism,interview,investigation',
    'news,journalism',
    'US',
  ],
  [
    'BBCNews',
    'BBC News',
    'en',
    'BBC News',
    'HARDtalk, Newsnight, and documentary strands.',
    'news,interview,documentary',
    'news,current-affairs',
    'GB',
  ],
  [
    'BBCInOurTime',
    'In Our Time',
    'en',
    'Melvyn Bragg',
    'Radio 4 seminar on video when posted.',
    'ideas,history,interview,longform',
    'ideas,education',
    'GB',
  ],
  [
    'bbcradio4',
    'BBC Radio 4',
    'en',
    'BBC Radio 4',
    'Start the Week, Analysis, and other talk hours.',
    'public-radio,interview,ideas',
    'ideas,culture',
    'GB',
  ],
  [
    'TheRestIsHistoryPodcast',
    'The Rest is History',
    'en',
    'Tom Holland|Dominic Sandbrook',
    'Two historians, one long conversation.',
    'history,conversation,longform',
    'history,ideas',
    'GB',
  ],
  [
    'TheRestIsPolitics',
    'The Rest is Politics',
    'en',
    'Alastair Campbell|Rory Stewart',
    'Political conversation from London.',
    'politics,conversation,longform',
    'current-affairs,ideas',
    'GB',
  ],
  [
    'GoalhangerPodcasts',
    'Goalhanger Podcasts',
    'en',
    'Goalhanger',
    'The Rest Is… family of talk shows.',
    'conversation,longform,interview',
    'culture,current-affairs',
    'GB',
  ],
  [
    'dancarlin',
    'Dan Carlin',
    'en',
    'Dan Carlin',
    'Hardcore History and Common Sense when posted.',
    'history,longform,storytelling',
    'history,ideas',
    'US',
  ],
  [
    'hardcorehistory',
    'Hardcore History',
    'en',
    'Dan Carlin',
    'Multi-hour history narratives.',
    'history,longform,storytelling',
    'history,ideas',
    'US',
  ],
  [
    'stuffyoushouldknow',
    'Stuff You Should Know',
    'en',
    'Josh Clark|Chuck Bryant',
    'Explainer conversations.',
    'explainer,conversation,education',
    'education,culture',
    'US',
  ],
  [
    'ologies',
    'Ologies',
    'en',
    'Alie Ward',
    'Interviews with scientists about their -ology.',
    'science,interviews,research,longform',
    'science,education',
    'US',
  ],
  [
    'sciencevs',
    'Science Vs',
    'en',
    'Wendy Zukerman',
    'Gimlet science investigations.',
    'science,journalism,explainer',
    'science,education',
    'US',
  ],
  [
    'sciencefriday',
    'Science Friday',
    'en',
    'Ira Flatow',
    'The public-radio science hour.',
    'science,public-radio,interviews,research',
    'science,education',
    'US',
  ],
  [
    'shortwave',
    'Short Wave',
    'en',
    'NPR',
    'NPR science desk conversations.',
    'science,public-radio,interview',
    'science,education',
    'US',
  ],
  [
    'planetmoney',
    'Planet Money',
    'en',
    'NPR',
    'Economics stories and interviews.',
    'economics,public-radio,explainer',
    'business,education',
    'US',
  ],
  [
    'howibuiltthis',
    'How I Built This',
    'en',
    'Guy Raz',
    'Founder interviews.',
    'interview,business,longform',
    'business,ideas',
    'US',
  ],
  [
    'tedradiohour',
    'TED Radio Hour',
    'en',
    'Manoush Zomorodi',
    'Ideas hour from NPR and TED.',
    'ideas,public-radio,interview',
    'ideas,education',
    'US',
  ],
  [
    'throughline',
    'Throughline',
    'en',
    'NPR',
    'History of the present, at length.',
    'history,public-radio,journalism',
    'history,news',
    'US',
  ],
  [
    'codeswitch',
    'Code Switch',
    'en',
    'NPR',
    'Race and culture conversations.',
    'culture,public-radio,interview',
    'culture,society-culture',
    'US',
  ],
  [
    'latinousa',
    'Latino USA',
    'en',
    'Maria Hinojosa',
    'Latino stories from a public-radio desk.',
    'culture,public-radio,latam,interview',
    'culture,journalism',
    'US',
  ],
  [
    'revealnews',
    'Reveal',
    'en',
    'The Center for Investigative Reporting',
    'Investigative hours.',
    'journalism,investigation,public-radio',
    'journalism,news',
    'US',
  ],
  [
    'propublica',
    'ProPublica',
    'en',
    'ProPublica',
    'Investigative briefings and talks.',
    'journalism,investigation',
    'journalism,news',
    'US',
  ],
  [
    'theintercept',
    'The Intercept',
    'en',
    'The Intercept',
    'Interviews and investigations.',
    'journalism,politics,interview',
    'news,current-affairs',
    'US',
  ],
  [
    'novaramedia',
    'Novara Media',
    'en',
    'Novara Media',
    'UK left interviews and analysis.',
    'politics,interview,longform',
    'current-affairs,ideas',
    'GB',
  ],
  [
    'doubleDownNews',
    'Double Down News',
    'en',
    'Double Down News',
    'Longer independent UK political films.',
    'politics,documentary,interview',
    'current-affairs,documentary',
    'GB',
  ],
  [
    'owenjones84',
    'Owen Jones',
    'en',
    'Owen Jones',
    'Political interviews from the UK left.',
    'politics,interview,longform',
    'current-affairs,ideas',
    'GB',
  ],
  [
    'themajorityreport',
    'The Majority Report',
    'en',
    'Sam Seder',
    'Daily political conversation.',
    'politics,interview,conversation',
    'current-affairs,ideas',
    'US',
  ],
  [
    'citationsneeded',
    'Citations Needed',
    'en',
    'Nima Shirazi|Adam Johnson',
    'Media-criticism conversations.',
    'politics,media,interview',
    'ideas,current-affairs',
    'US',
  ],
  [
    'behindthebastards',
    'Behind the Bastards',
    'en',
    'Robert Evans',
    'Long historical monologues and guests.',
    'history,politics,storytelling,longform',
    'history,society-culture',
    'US',
  ],
  [
    'coolzone',
    'Cool Zone Media',
    'en',
    'Cool Zone Media',
    'It Could Happen Here and sister talk shows.',
    'politics,interview,longform',
    'current-affairs,ideas',
    'US',
  ],
  [
    'jacobin',
    'Jacobin',
    'en',
    'Jacobin',
    'Socialist interviews and panels.',
    'politics,interview,ideas',
    'current-affairs,ideas',
    'US',
  ],
  [
    'currentaffairs',
    'Current Affairs',
    'en',
    'Nathan J. Robinson',
    'Magazine interviews on video.',
    'politics,interview,ideas',
    'ideas,current-affairs',
    'US',
  ],
  [
    'thenation',
    'The Nation',
    'en',
    'The Nation',
    'Magazine conversations.',
    'politics,interview,journalism',
    'current-affairs,journalism',
    'US',
  ],
  [
    'newyorker',
    'The New Yorker',
    'en',
    'The New Yorker',
    'Writer interviews and live events.',
    'interview,culture,journalism,longform',
    'culture,ideas',
    'US',
  ],
  [
    'TheAtlantic',
    'The Atlantic',
    'en',
    'The Atlantic',
    'Ideas interviews.',
    'interview,ideas,journalism',
    'ideas,current-affairs',
    'US',
  ],
  [
    'vox',
    'Vox',
    'en',
    'Vox',
    'Explainers and The Gray Area interviews.',
    'explainer,interview,ideas',
    'education,current-affairs',
    'US',
  ],
  [
    'johnnyharris',
    'Johnny Harris',
    'en',
    'Johnny Harris',
    'Visual geopolitics, longer than a short.',
    'geopolitics,documentary,explainer',
    'documentary,education',
    'US',
  ],
  [
    'wendoverproductions',
    'Wendover Productions',
    'en',
    'Sam from Wendover',
    'Logistics and geography at essay length.',
    'explainer,geography,education',
    'education,documentary',
    'US',
  ],
  [
    'RealEngineering',
    'Real Engineering',
    'en',
    'Brian McManus',
    'Engineering essays.',
    'science,engineering,explainer',
    'education,science',
    'IE',
  ],
  [
    'PracticalEngineeringChannel',
    'Practical Engineering',
    'en',
    'Grady Hillhouse',
    'Civil-engineering explainers.',
    'science,engineering,education',
    'education,science',
    'US',
  ],
  [
    'PerunGamingAU',
    'Perun',
    'en',
    'Perun',
    'Hour-plus defence-economics briefings.',
    'geopolitics,energy,explainer,longform',
    'current-affairs,education',
    'AU',
  ],
  [
    'caspianreport',
    'CaspianReport',
    'en',
    'Shirvan Neftchi',
    'Geopolitical essays.',
    'geopolitics,explainer',
    'current-affairs,education',
    'NL',
  ],
  [
    'polymatter',
    'PolyMatter',
    'en',
    'PolyMatter',
    'Country and industry essays.',
    'geopolitics,explainer,business',
    'education,current-affairs',
    'US',
  ],
  [
    'ColdFusionTV',
    'ColdFusion',
    'en',
    'Dagogo Altraide',
    'Tech-history essays.',
    'tech,history,explainer',
    'education,technology',
    'AU',
  ],
  [
    'crashcourse',
    'Crash Course',
    'en',
    'Complexly',
    'Course-length educational series.',
    'education,lecture,science,history',
    'education,history',
    'US',
  ],
  [
    'theschooloflifetv',
    'The School of Life',
    'en',
    'The School of Life',
    'Philosophy and culture essays.',
    'philosophy,culture,education',
    'ideas,education',
    'GB',
  ],
  [
    'philosophizethis',
    'Philosophize This!',
    'en',
    'Stephen West',
    'History of philosophy as a talk series.',
    'philosophy,lecture,education,longform',
    'ideas,education',
    'US',
  ],
  [
    'historyofphilosophy',
    'History of Philosophy Without Any Gaps',
    'en',
    'Peter Adamson',
    'Academic philosophy talks.',
    'philosophy,lecture,education',
    'ideas,education',
    'US',
  ],
  [
    'verybadwizards',
    'Very Bad Wizards',
    'en',
    'Tamler Sommers|David Pizarro',
    'Philosophy and psychology conversations.',
    'philosophy,conversation,interview',
    'ideas,science',
    'US',
  ],
  [
    'rationallyspeaking',
    'Rationally Speaking',
    'en',
    'Julia Galef|Massimo Pigliucci',
    'Reasoning interviews.',
    'science,ideas,interview',
    'ideas,science',
    'US',
  ],
  [
    'dwdocumentary',
    'DW Documentary',
    'en',
    'Deutsche Welle',
    'Full documentaries from Germany.',
    'documentary,journalism,longform',
    'documentary,news',
    'DE',
  ],
  [
    'france24_en',
    'FRANCE 24 English',
    'en',
    'France 24',
    'The Interview and longer reports.',
    'news,interview,documentary',
    'news,current-affairs',
    'FR',
  ],
  [
    'trtworld',
    'TRT World',
    'en',
    'TRT World',
    'Roundtables and longer reports.',
    'news,interview,documentary',
    'news,current-affairs',
    'TR',
  ],
  [
    'ABCNewsAustralia',
    'ABC News Australia',
    'en',
    'ABC',
    'Four Corners, Q+A, and interview hours.',
    'news,interview,public-media',
    'news,current-affairs',
    'AU',
  ],
  [
    'FourCornersABC',
    'Four Corners',
    'en',
    'ABC',
    'Australian long investigations.',
    'documentary,journalism,investigation',
    'documentary,news',
    'AU',
  ],
  [
    'cbcnews',
    'CBC News',
    'en',
    'CBC',
    'The National and interview programmes.',
    'news,interview,public-media',
    'news,current-affairs',
    'CA',
  ],
  [
    'TheNationalCBC',
    'The National',
    'en',
    'CBC',
    'Canadian flagship news hour.',
    'news,public-media,journalism',
    'news,current-affairs',
    'CA',
  ],
  [
    'guardiannews',
    'Guardian News',
    'en',
    'The Guardian',
    'Interviews and live events.',
    'news,interview,journalism',
    'news,current-affairs',
    'GB',
  ],
  [
    'FinancialTimes',
    'Financial Times',
    'en',
    'Financial Times',
    'FT News Briefing and longer talks.',
    'news,business,interview',
    'news,business',
    'GB',
  ],
  [
    'EconomistPodcasts',
    'The Economist Podcasts',
    'en',
    'The Economist',
    'Editor conversations on video.',
    'news,ideas,interview',
    'news,current-affairs',
    'GB',
  ],
  [
    'BloombergTV',
    'Bloomberg Television',
    'en',
    'Bloomberg',
    'Odd Lots and longer market conversations.',
    'business,interview,economics',
    'business,news',
    'US',
  ],
  [
    'OddLots',
    'Odd Lots',
    'en',
    'Joe Weisenthal|Tracy Alloway',
    'Markets conversations that go long.',
    'economics,interview,energy,longform',
    'business,ideas',
    'US',
  ],
  [
    'volts',
    'Volts',
    'en',
    'David Roberts',
    'Clean-energy interviews.',
    'energy,climate,interview,longform',
    'science,current-affairs',
    'US',
  ],
  [
    'columbiaenergy',
    'Columbia Energy Exchange',
    'en',
    'Columbia SIPA',
    'Energy-policy conversations.',
    'energy,climate,interview,policy',
    'science,current-affairs',
    'US',
  ],
  [
    'resourcesradio',
    'Resources Radio',
    'en',
    'Resources for the Future',
    'Environment and energy interviews.',
    'energy,climate,interview,ecology',
    'science,current-affairs',
    'US',
  ],
  [
    'energygang',
    'The Energy Gang',
    'en',
    'Wood Mackenzie',
    'Energy-transition conversations.',
    'energy,climate,interview',
    'business,science',
    'US',
  ],
  [
    'amatterofdegrees',
    'A Matter of Degrees',
    'en',
    'Leah Stokes|Kate Marvel',
    'Climate-politics conversations.',
    'climate,politics,interview,ecology',
    'science,current-affairs',
    'US',
  ],
  [
    'outrageandoptimism',
    'Outrage + Optimism',
    'en',
    'Christiana Figueres',
    'Climate-diplomacy conversations.',
    'climate,interview,politics',
    'current-affairs,science',
    'GB',
  ],
  [
    'mothersofinvention',
    'Mothers of Invention',
    'en',
    'Mary Robinson|Maeve Higgins',
    'Feminist climate conversations.',
    'climate,interview,ecojustice',
    'society-culture,science',
    'IE',
  ],
  [
    'howtosaveaplanet',
    'How to Save a Planet',
    'en',
    'Gimlet',
    'Solutions-climate conversations.',
    'climate,interview,ecology',
    'science,education',
    'US',
  ],
  [
    'extinctionrebellion',
    'Extinction Rebellion',
    'en',
    'Extinction Rebellion',
    'Talks and briefings from the climate movement.',
    'climate,ecojustice,organizing',
    'society-culture,news',
    'GB',
  ],
  [
    'breakthroughinstitute',
    'The Breakthrough Institute',
    'en',
    'Breakthrough Institute',
    'Ecomodernist debates and talks.',
    'climate,energy,ideas,interview',
    'ideas,science',
    'US',
  ],
  [
    'conanobrien',
    'Conan O’Brien Needs a Friend',
    'en',
    'Conan O’Brien',
    'Long comedy interviews.',
    'interview,conversation,comedy,longform',
    'culture,society-culture',
    'US',
  ],
  [
    'smartless',
    'SmartLess',
    'en',
    'Jason Bateman|Sean Hayes|Will Arnett',
    'Long celebrity conversations.',
    'interview,conversation,comedy,longform',
    'culture,society-culture',
    'US',
  ],
  [
    'armchairexpert',
    'Armchair Expert',
    'en',
    'Dax Shepard',
    'Long interviews.',
    'interview,conversation,longform',
    'culture,society-culture',
    'US',
  ],
  [
    'WTFpod',
    'WTF with Marc Maron',
    'en',
    'Marc Maron',
    'The garage interview.',
    'interview,conversation,longform',
    'culture,society-culture',
    'US',
  ],
  [
    'duncantrussell',
    'Duncan Trussell Family Hour',
    'en',
    'Duncan Trussell',
    'Long, strange conversations.',
    'interview,conversation,longform',
    'culture,ideas',
    'US',
  ],
  [
    'thispastweekend',
    'This Past Weekend',
    'en',
    'Theo Von',
    'Long comedy conversations.',
    'interview,conversation,comedy,longform',
    'culture,society-culture',
    'US',
  ],
  [
    'flagrant2',
    'Flagrant',
    'en',
    'Andrew Schulz',
    'Long comedy conversations.',
    'interview,conversation,comedy,longform',
    'culture,society-culture',
    'US',
  ],
  [
    'newheightshow',
    'New Heights',
    'en',
    'Jason Kelce|Travis Kelce',
    'Long sports conversations.',
    'interview,sports,conversation,longform',
    'culture,sports',
    'US',
  ],
  [
    'billsimmons',
    'Bill Simmons',
    'en',
    'Bill Simmons',
    'The Bill Simmons Podcast on video.',
    'interview,sports,culture,longform',
    'culture,sports',
    'US',
  ],
  [
    'theringer',
    'The Ringer',
    'en',
    'The Ringer',
    'Rewatchables and talk hours.',
    'interview,culture,sports,longform',
    'culture,society-culture',
    'US',
  ],
  [
    'revisionisthistory',
    'Revisionist History',
    'en',
    'Malcolm Gladwell',
    'Seasonal essay-podcasts on video.',
    'storytelling,history,ideas,longform',
    'ideas,history',
    'US',
  ],
  [
    'brokenrecord',
    'Broken Record',
    'en',
    'Rick Rubin|Malcolm Gladwell',
    'Long musician interviews.',
    'interview,music,longform',
    'culture,music',
    'US',
  ],
  [
    'songexploder',
    'Song Exploder',
    'en',
    'Hrishikesh Hirway',
    'Musicians unpack one song.',
    'interview,music,storytelling',
    'culture,music',
    'US',
  ],
  [
    'dissectpodcast',
    'Dissect',
    'en',
    'Cole Cuchna',
    'Album-length music essays.',
    'music,education,longform',
    'culture,education',
    'US',
  ],
  [
    'questlovesupreme',
    'Questlove Supreme',
    'en',
    'Questlove',
    'Long music conversations.',
    'interview,music,longform',
    'culture,music',
    'US',
  ],
  [
    'hotones',
    'Hot Ones',
    'en',
    'Sean Evans|First We Feast',
    'Interview series (spicy, but still an interview).',
    'interview,culture,conversation',
    'culture,society-culture',
    'US',
  ],
  [
    'clubshayshay',
    'Club Shay Shay',
    'en',
    'Shannon Sharpe',
    'Long sports and culture interviews.',
    'interview,sports,conversation,longform',
    'culture,sports',
    'US',
  ],
  [
    'allthesmoke',
    'All The Smoke',
    'en',
    'Matt Barnes|Stephen Jackson',
    'Long athlete conversations.',
    'interview,sports,conversation,longform',
    'culture,sports',
    'US',
  ],
  [
    'breakfastclubpower1051',
    'The Breakfast Club',
    'en',
    'Charlamagne tha God',
    'Hip-hop interview radio on video.',
    'interview,culture,conversation',
    'culture,society-culture',
    'US',
  ],
  [
    'impaulsive',
    'Impaulsive',
    'en',
    'Logan Paul',
    'Long pop-culture interviews.',
    'interview,conversation,longform',
    'culture,society-culture',
    'US',
  ],
  [
    'contraPoints',
    'ContraPoints',
    'en',
    'Natalie Wynn',
    'Long video essays on culture and politics.',
    'essay,politics,culture,longform',
    'ideas,culture',
    'US',
  ],
  [
    'philosophyTube',
    'Philosophy Tube',
    'en',
    'Abigail Thorn',
    'Long philosophy essays.',
    'philosophy,essay,education,longform',
    'ideas,education',
    'GB',
  ],
  [
    'hbomberguy',
    'hbomberguy',
    'en',
    'Harris Brewis',
    'Long investigative video essays.',
    'essay,investigation,longform',
    'ideas,culture',
    'GB',
  ],
  [
    'foldingideas',
    'Folding Ideas',
    'en',
    'Dan Olson',
    'Long media-criticism essays.',
    'essay,media,longform',
    'ideas,culture',
    'CA',
  ],
  [
    'inthethink',
    'Innuendo Studios',
    'en',
    'Ian Danskin',
    'Political video essays.',
    'essay,politics,longform',
    'ideas,current-affairs',
    'US',
  ],
  [
    'sarahz',
    'Sarah Z',
    'en',
    'Sarah Z',
    'Internet-culture essays at length.',
    'essay,culture,longform',
    'culture,ideas',
    'CA',
  ],
  [
    'jacobgeller',
    'Jacob Geller',
    'en',
    'Jacob Geller',
    'Long essays on games, art, and dread.',
    'essay,culture,longform',
    'culture,ideas',
    'US',
  ],
  [
    'polyhistor',
    'Lindsay Ellis',
    'en',
    'Lindsay Ellis',
    'Long film essays (archive and new).',
    'essay,film,longform',
    'culture,ideas',
    'US',
  ],

  // Spanish — Spain
  [
    'TheWildProject',
    'The Wild Project',
    'es',
    'Jordi Wild',
    'Entrevistas largas en español: ciencia, política y cultura.',
    'interview,conversation,longform,spanish',
    'society-culture,ideas',
    'ES',
  ],
  [
    'jordiwild',
    'Jordi Wild',
    'es',
    'Jordi Wild',
    'El canal del anfitrión de The Wild Project.',
    'interview,conversation,longform,spanish',
    'society-culture,ideas',
    'ES',
  ],
  [
    'carnecudad',
    'Carne Cruda',
    'es',
    'Javier Gallego',
    'Radio independiente: política y cultura en largo.',
    'politics,culture,public-radio,spanish,interview',
    'current-affairs,culture',
    'ES',
  ],
  [
    'eldiarioes',
    'elDiario.es',
    'es',
    'elDiario.es',
    'Un tema al día y entrevistas.',
    'news,interview,spanish,journalism',
    'news,current-affairs',
    'ES',
  ],
  [
    'elpais',
    'EL PAÍS',
    'es',
    'EL PAÍS',
    'Conversaciones y reportajes largos.',
    'news,interview,spanish,journalism',
    'news,culture',
    'ES',
  ],
  [
    'cadenaser',
    'Cadena SER',
    'es',
    'Cadena SER',
    'Hoy por Hoy, A vivir, y horas de radio en video.',
    'public-radio,interview,news,spanish',
    'news,culture',
    'ES',
  ],
  [
    'rtve',
    'RTVE',
    'es',
    'RTVE',
    'Informe Semanal, Documentos TV, entrevistas.',
    'public-media,documentary,interview,spanish',
    'news,documentary',
    'ES',
  ],
  [
    'laSexta',
    'laSexta',
    'es',
    'laSexta',
    'Al Rojo Vivo, Salvados clips, entrevistas.',
    'news,interview,politics,spanish',
    'news,current-affairs',
    'ES',
  ],
  [
    'salvadoslasexta',
    'Salvados',
    'es',
    'Jordi Évole|laSexta',
    'Entrevistas y crónicas largas.',
    'interview,journalism,spanish,longform',
    'journalism,current-affairs',
    'ES',
  ],
  [
    'loDeEvole',
    'Lo de Évole',
    'es',
    'Jordi Évole',
    'Entrevistas largas en laSexta.',
    'interview,journalism,spanish,longform',
    'journalism,culture',
    'ES',
  ],
  [
    'equipoinvestigacion',
    'Equipo de Investigación',
    'es',
    'laSexta',
    'Reportajes de investigación.',
    'investigation,journalism,spanish',
    'journalism,documentary',
    'ES',
  ],
  [
    'anaPastor_tve',
    'El Objetivo',
    'es',
    'Ana Pastor',
    'Entrevistas políticas.',
    'interview,politics,spanish,journalism',
    'news,current-affairs',
    'ES',
  ],
  [
    'enlafrontera',
    'En la Frontera',
    'es',
    'Gonzalo Boye',
    'Conversaciones políticas largas.',
    'politics,interview,spanish,longform',
    'current-affairs,ideas',
    'ES',
  ],
  [
    'quantumfracture',
    'Quantum Fracture',
    'es',
    'José Luis Crespo',
    'Física en español, a veces a escala de conferencia.',
    'science,education,spanish,explainer',
    'science,education',
    'ES',
  ],
  [
    'dateunvoltio',
    'Date un Voltio',
    'es',
    'Javier Santaolalla',
    'Física y conversaciones científicas.',
    'science,education,spanish,interview',
    'science,education',
    'ES',
  ],
  [
    'cdeciencia',
    'C de Ciencia',
    'es',
    'Javier Yanes',
    'Ciencia en conversación.',
    'science,education,spanish',
    'science,education',
    'ES',
  ],
  [
    'derivando',
    'Derivando',
    'es',
    'Eduardo Sáenz de Cabezón',
    'Matemáticas habladas.',
    'science,maths,education,spanish',
    'science,education',
    'ES',
  ],
  [
    'jaimealtozano',
    'Jaime Altozano',
    'es',
    'Jaime Altozano',
    'Ensayos musicales largos.',
    'music,education,essay,spanish,longform',
    'culture,education',
    'ES',
  ],
  [
    'dotcsv',
    'Dot CSV',
    'es',
    'Carlos Santana',
    'IA y ciencia de datos en español.',
    'ai,science,education,spanish',
    'science,education',
    'ES',
  ],
  [
    'nategentile7',
    'Nate Gentile',
    'es',
    'Nate Gentile',
    'Tech largo en español.',
    'tech,education,spanish,longform',
    'technology,education',
    'ES',
  ],
  [
    'bbcmundo',
    'BBC News Mundo',
    'es',
    'BBC Mundo',
    'Reportajes y entrevistas en español.',
    'news,interview,spanish,journalism',
    'news,current-affairs',
    'GB',
  ],
  [
    'DWespanol',
    'DW Español',
    'es',
    'Deutsche Welle',
    'Documentales y entrevistas en español.',
    'documentary,news,spanish,interview',
    'news,documentary',
    'DE',
  ],
  [
    'france24_es',
    'FRANCE 24 Español',
    'es',
    'France 24',
    'El debate y reportajes.',
    'news,interview,spanish',
    'news,current-affairs',
    'FR',
  ],
  [
    'cnnee',
    'CNN en Español',
    'es',
    'CNN',
    'Entrevistas y mesas en español.',
    'news,interview,spanish',
    'news,current-affairs',
    'US',
  ],
  [
    '3cat',
    '3Cat',
    'es',
    '3Cat',
    'Medio público catalán: entrevistas y documentales (también en catalán).',
    'public-media,interview,catalan,spanish',
    'news,culture',
    'ES',
  ],
  [
    'tv3cat',
    'TV3',
    'ca',
    'TV3',
    'Informatius i entrevistes en català.',
    'public-media,interview,catalan',
    'news,culture',
    'ES',
  ],
  [
    'catalunyaradio',
    'Catalunya Ràdio',
    'ca',
    'Catalunya Ràdio',
    'Ràdio pública en vídeo.',
    'public-radio,interview,catalan',
    'news,culture',
    'ES',
  ],
  [
    'estirandoelchicle',
    'Estirando el chicle',
    'es',
    'Carolina Iglesias|Victoria Martín',
    'Conversaciones largas de humor y cultura.',
    'conversation,comedy,culture,spanish,longform',
    'culture,society-culture',
    'ES',
  ],
  [
    'lapijaylaquinqui',
    'La Pija y la Quinqui',
    'es',
    'La Pija y la Quinqui',
    'Conversación cultural en español.',
    'conversation,culture,spanish,longform',
    'culture,society-culture',
    'ES',
  ],
  [
    'buenismobien',
    'Buenismo Bien',
    'es',
    'Buenismo Bien',
    'Conversación política con humor.',
    'politics,conversation,spanish',
    'current-affairs,culture',
    'ES',
  ],
  [
    'radioprimaverasound',
    'Radio Primavera Sound',
    'es',
    'Primavera Sound',
    'Entrevistas musicales largas.',
    'interview,music,spanish,longform',
    'culture,music',
    'ES',
  ],

  // Spanish — Mexico
  [
    'aristeguinoticias',
    'Aristegui Noticias',
    'es',
    'Carmen Aristegui',
    'Entrevistas y mesas de investigación.',
    'news,interview,investigation,spanish',
    'news,journalism',
    'MX',
  ],
  [
    'latinus_us',
    'Latinus',
    'es',
    'Latinus',
    'Periodismo y entrevistas largas desde México.',
    'news,interview,spanish,journalism',
    'news,current-affairs',
    'MX',
  ],
  [
    'sinembargo',
    'SinEmbargo Al Aire',
    'es',
    'SinEmbargo',
    'Mesas y entrevistas.',
    'news,interview,spanish',
    'news,current-affairs',
    'MX',
  ],
  [
    'elpulsodelarepublica',
    'El Pulso de la República',
    'es',
    'Chumel Torres',
    'Monólogo político largo.',
    'politics,satire,spanish,longform',
    'current-affairs,culture',
    'MX',
  ],
  [
    'sopitas',
    'Sopitas',
    'es',
    'Sopitas',
    'Cultura y conversaciones.',
    'culture,interview,spanish',
    'culture,society-culture',
    'MX',
  ],
  [
    'plumasatomicas',
    'Plumas Atómicas',
    'es',
    'Plumas Atómicas',
    'Análisis político en video.',
    'politics,news,spanish',
    'current-affairs,news',
    'MX',
  ],
  [
    'animalpolitico',
    'Animal Político',
    'es',
    'Animal Político',
    'Periodismo explicado y entrevistas.',
    'journalism,news,spanish,interview',
    'news,journalism',
    'MX',
  ],
  [
    'proceso',
    'Proceso',
    'es',
    'Proceso',
    'Revista de investigación en video.',
    'journalism,investigation,spanish',
    'journalism,news',
    'MX',
  ],
  [
    'milenio',
    'Milenio',
    'es',
    'Milenio',
    'Entrevistas y noticieros largos.',
    'news,interview,spanish',
    'news,current-affairs',
    'MX',
  ],
  [
    'imagennoticias',
    'Imagen Noticias',
    'es',
    'Imagen',
    'Noticias y mesas.',
    'news,interview,spanish',
    'news,current-affairs',
    'MX',
  ],
  [
    'lopez-doriga',
    'Joaquín López-Dóriga',
    'es',
    'Joaquín López-Dóriga',
    'Entrevistas políticas.',
    'news,interview,politics,spanish',
    'news,current-affairs',
    'MX',
  ],
  [
    'cirogomezleyva',
    'Ciro Gómez Leyva',
    'es',
    'Ciro Gómez Leyva',
    'Mesa matutina larga.',
    'news,interview,spanish',
    'news,current-affairs',
    'MX',
  ],
  [
    'adelamicha',
    'Adela Micha',
    'es',
    'Adela Micha',
    'Entrevistas.',
    'news,interview,spanish',
    'news,current-affairs',
    'MX',
  ],
  [
    'seregalandudas',
    'Se Regalan Dudas',
    'es',
    'Se Regalan Dudas',
    'Conversaciones largas sobre vida y cultura.',
    'conversation,interview,spanish,longform',
    'culture,society-culture',
    'MX',
  ],
  [
    'creativopodcast',
    'Creativo',
    'es',
    'Roberto Martínez',
    'Entrevistas creativas largas.',
    'interview,conversation,spanish,longform',
    'culture,ideas',
    'MX',
  ],
  [
    'parenelpedo',
    'Paren El Pedo',
    'es',
    'Paren El Pedo',
    'Conversación política mexicana.',
    'politics,conversation,spanish',
    'current-affairs,culture',
    'MX',
  ],
  [
    'leyendaslegendarias',
    'Leyendas Legendarias',
    'es',
    'José Antonio Badía|Tony Navarrete',
    'Historias y comedia en formato largo.',
    'storytelling,comedy,spanish,longform',
    'culture,storytelling',
    'MX',
  ],
  [
    'lacotorrisa',
    'La Cotorrisa',
    'es',
    'La Cotorrisa',
    'Conversación cómica larga.',
    'conversation,comedy,spanish,longform',
    'culture,society-culture',
    'MX',
  ],
  [
    'relatonacional',
    'Relato Nacional',
    'es',
    'Relato Nacional',
    'Crónica chilena / latam en video.',
    'storytelling,crónica,spanish,longform',
    'storytelling,culture',
    'CL',
  ],

  // Spanish — Andes / Colombia / Southern Cone
  [
    'lawradio',
    'La W',
    'es',
    'La W Radio',
    'Mañanas y entrevistas colombianas.',
    'news,interview,public-radio,spanish',
    'news,current-affairs',
    'CO',
  ],
  [
    'bluradio',
    'Blu Radio',
    'es',
    'Blu Radio',
    'Mañanas Blu y mesas.',
    'news,interview,spanish',
    'news,current-affairs',
    'CO',
  ],
  [
    'caracolradio',
    'Caracol Radio',
    'es',
    'Caracol Radio',
    'Radio hablada colombiana en video.',
    'news,interview,spanish',
    'news,current-affairs',
    'CO',
  ],
  [
    'RevistaSemana',
    'Revista Semana',
    'es',
    'Semana',
    'Entrevistas y Vicky en Semana.',
    'news,interview,politics,spanish',
    'news,current-affairs',
    'CO',
  ],
  [
    'ElTiempo',
    'El Tiempo',
    'es',
    'El Tiempo',
    'Entrevistas y reportajes.',
    'news,interview,spanish,journalism',
    'news,current-affairs',
    'CO',
  ],
  [
    'elespectador',
    'El Espectador',
    'es',
    'El Espectador',
    'La Pulla y periodismo en video.',
    'news,journalism,spanish,interview',
    'news,journalism',
    'CO',
  ],
  [
    'lasillavacia',
    'La Silla Vacía',
    'es',
    'La Silla Vacía',
    'Política colombiana explicada.',
    'politics,journalism,spanish,explainer',
    'news,current-affairs',
    'CO',
  ],
  [
    'pacifistacol',
    'Pacifista!',
    'es',
    'Pacifista',
    'Paz, juventud y crónicas.',
    'culture,peace,spanish,journalism',
    'culture,journalism',
    'CO',
  ],
  [
    'voraginecol',
    'Vorágine',
    'es',
    'Vorágine',
    'Investigación independiente.',
    'journalism,investigation,spanish',
    'journalism,news',
    'CO',
  ],
  [
    'centroamericas',
    'Centro',
    'es',
    'Radio Ambulante Estudios',
    'Historias centroamericanas.',
    'crónica,latam,spanish,storytelling',
    'storytelling,journalism',
    'US',
  ],
  [
    'rppnoticias',
    'RPP Noticias',
    'es',
    'RPP',
    'Radio hablada peruana.',
    'news,interview,spanish',
    'news,current-affairs',
    'PE',
  ],
  [
    'laencerrona',
    'La Encerrona',
    'es',
    'Marco Sifuentes',
    'Política peruana diaria, a veces en largo.',
    'politics,news,spanish,explainer',
    'news,current-affairs',
    'PE',
  ],
  [
    'ojopublico',
    'Ojo Público',
    'es',
    'Ojo Público',
    'Investigación peruana.',
    'journalism,investigation,spanish',
    'journalism,news',
    'PE',
  ],
  [
    'idlreporteros',
    'IDL-Reporteros',
    'es',
    'IDL-Reporteros',
    'Investigación.',
    'journalism,investigation,spanish',
    'journalism,news',
    'PE',
  ],
  [
    'waykape',
    'Wayka',
    'es',
    'Wayka',
    'Periodismo digital peruano.',
    'news,journalism,spanish',
    'news,journalism',
    'PE',
  ],
  [
    'gk_ecuador',
    'GK',
    'es',
    'GK',
    'Periodismo digital ecuatoriano: género, ambiente, política.',
    'journalism,ecology,spanish,andes',
    'journalism,culture',
    'EC',
  ],
  [
    'labarraespaciadora',
    'La Barra Espaciadora',
    'es',
    'La Barra Espaciadora',
    'Periodismo independiente del Ecuador.',
    'journalism,politics,spanish,andes',
    'journalism,news',
    'EC',
  ],
  [
    'radiopichincha',
    'Radio Pichincha',
    'es',
    'Radio Pichincha',
    'Radio pública ecuatoriana en video.',
    'public-radio,news,spanish,andes',
    'news,current-affairs',
    'EC',
  ],
  [
    'cooperativa',
    'Cooperativa',
    'es',
    'Radio Cooperativa',
    'Radio hablada chilena.',
    'news,interview,spanish',
    'news,current-affairs',
    'CL',
  ],
  [
    'biobio',
    'BioBioChile',
    'es',
    'Radio Bío Bío',
    'Noticias y entrevistas.',
    'news,interview,spanish',
    'news,current-affairs',
    'CL',
  ],
  [
    'ciperchile',
    'CIPER',
    'es',
    'CIPER',
    'Investigación chilena.',
    'journalism,investigation,spanish',
    'journalism,news',
    'CL',
  ],
  [
    'interferenciachile',
    'Interferencia',
    'es',
    'Interferencia',
    'Periodismo independiente.',
    'journalism,politics,spanish',
    'journalism,news',
    'CL',
  ],
  [
    'cnnchile',
    'CNN Chile',
    'es',
    'CNN Chile',
    'Entrevistas y mesas.',
    'news,interview,spanish',
    'news,current-affairs',
    'CL',
  ],
  [
    'adnradiochile',
    'ADN Radio',
    'es',
    'ADN',
    'Mañanas radiales chilenas.',
    'news,interview,spanish',
    'news,current-affairs',
    'CL',
  ],
  [
    'filonews',
    'Filo.news',
    'es',
    'Filo.news',
    'Cultura y actualidad argentina.',
    'culture,news,spanish,interview',
    'culture,news',
    'AR',
  ],
  [
    'c5n',
    'C5N',
    'es',
    'C5N',
    'Mesas políticas argentinas.',
    'news,politics,spanish,interview',
    'news,current-affairs',
    'AR',
  ],
  [
    'todonoticias',
    'TN',
    'es',
    'TN',
    'Todo Noticias: entrevistas.',
    'news,interview,spanish',
    'news,current-affairs',
    'AR',
  ],
  [
    'lnmas',
    'LN+',
    'es',
    'La Nación +',
    'Mesas y entrevistas.',
    'news,interview,spanish',
    'news,current-affairs',
    'AR',
  ],
  [
    'elmetodorebord',
    'El Método Rebord',
    'es',
    'Tomás Rebord',
    'Entrevistas larguísimas argentinas.',
    'interview,conversation,spanish,longform',
    'culture,ideas',
    'AR',
  ],
  [
    'luzutv',
    'Luzu TV',
    'es',
    'Luzu TV',
    'Streaming de conversación argentina.',
    'conversation,culture,spanish,longform',
    'culture,society-culture',
    'AR',
  ],
  [
    'olgaenvivo',
    'Olga',
    'es',
    'Olga',
    'Conversación y actualidad en streaming.',
    'conversation,culture,spanish',
    'culture,society-culture',
    'AR',
  ],
  [
    'futurock',
    'Futurock',
    'es',
    'Futurock',
    'Radio cultural argentina en video.',
    'culture,politics,spanish,public-radio',
    'culture,current-affairs',
    'AR',
  ],
  [
    'eldestape',
    'El Destape',
    'es',
    'El Destape',
    'Política argentina en largo.',
    'politics,news,spanish,interview',
    'news,current-affairs',
    'AR',
  ],
  [
    'enperspectiva',
    'En Perspectiva',
    'es',
    'Emiliano Cotelo',
    'Radio uruguaya de entrevistas.',
    'interview,news,spanish,public-radio',
    'news,current-affairs',
    'UY',
  ],
  [
    'notocannada',
    'No Toquen Nada',
    'es',
    'No Toquen Nada',
    'Magazine radial uruguayo.',
    'culture,conversation,spanish',
    'culture,society-culture',
    'UY',
  ],
  [
    'delsoluy',
    'DelSol',
    'es',
    'DelSol',
    'Radio uruguaya en video.',
    'news,interview,spanish',
    'news,culture',
    'UY',
  ],
  [
    'ntn24',
    'NTN24',
    'es',
    'NTN24',
    'Noticias y mesas andinas / latam.',
    'news,interview,spanish',
    'news,current-affairs',
    'CO',
  ],
  [
    'univision',
    'Univision Noticias',
    'es',
    'Univision',
    'Noticias y entrevistas en español de EE. UU.',
    'news,interview,spanish',
    'news,current-affairs',
    'US',
  ],
  [
    'telemundo',
    'Noticias Telemundo',
    'es',
    'Telemundo',
    'Noticias en español.',
    'news,interview,spanish',
    'news,current-affairs',
    'US',
  ],
  [
    'extraordinariopod',
    'Extraordinario',
    'es',
    'Daniel Alarcón',
    'Historias narrativas en español.',
    'storytelling,crónica,spanish,longform',
    'storytelling,journalism',
    'US',
  ],

  // Portuguese / other Europe / Asia / Africa talk
  [
    'inteligencia-ltda',
    'Inteligência Ltda.',
    'pt',
    'Rogério Z. Viletram',
    'Entrevistas longas em português.',
    'interview,conversation,longform',
    'society-culture,ideas',
    'BR',
  ],
  [
    'podpah',
    'Podpah',
    'pt',
    'Igão|Mítico',
    'Entrevistas longas brasileiras.',
    'interview,conversation,longform',
    'culture,society-culture',
    'BR',
  ],
  [
    'flowpodcast',
    'Flow Podcast',
    'pt',
    'Flow Podcast',
    'Mesa longa em português.',
    'interview,conversation,longform',
    'culture,society-culture',
    'BR',
  ],
  [
    'jovempan',
    'Jovem Pan',
    'pt',
    'Jovem Pan',
    'Rádio falada brasileira.',
    'news,interview',
    'news,current-affairs',
    'BR',
  ],
  [
    'bbcbrasil',
    'BBC News Brasil',
    'pt',
    'BBC Brasil',
    'Reportagens e entrevistas.',
    'news,interview,journalism',
    'news,current-affairs',
    'GB',
  ],
  [
    'g1',
    'g1',
    'pt',
    'g1',
    'Entrevistas e reportagens.',
    'news,interview,journalism',
    'news,current-affairs',
    'BR',
  ],
  [
    'tvuol',
    'UOL',
    'pt',
    'UOL',
    'Conversas e jornalismo.',
    'news,interview',
    'news,current-affairs',
    'BR',
  ],
  [
    'meduza',
    'Meduza',
    'ru',
    'Meduza',
    'Independent Russian-language interviews (exile desk).',
    'news,interview,journalism',
    'news,current-affairs',
    'LV',
  ],
  [
    'tvrain',
    'TV Rain / Dozhd',
    'ru',
    'TV Rain',
    'Independent Russian talk, from exile.',
    'news,interview,politics',
    'news,current-affairs',
    'NL',
  ],
  [
    'lexfridmanru',
    'Lex Fridman (clips ru)',
    'ru',
    'Lex Fridman',
    'Russian-language conversation clips when posted.',
    'interview,longform,ideas',
    'ideas,science',
    'US',
  ],
  [
    'dwnews',
    'DW News',
    'en',
    'Deutsche Welle',
    'Conflict Zone and long interviews.',
    'news,interview,documentary',
    'news,current-affairs',
    'DE',
  ],
  [
    'zdf',
    'ZDF',
    'de',
    'ZDF',
    'Aspekte, documentaries, and talk.',
    'public-media,documentary,interview',
    'news,culture',
    'DE',
  ],
  [
    'ard',
    'ARD',
    'de',
    'ARD',
    'German public-service talk and documentary.',
    'public-media,documentary,interview',
    'news,culture',
    'DE',
  ],
  [
    'funkofficial',
    'funk',
    'de',
    'funk',
    'Young public-service explainers and talk.',
    'education,interview,public-media',
    'education,culture',
    'DE',
  ],
  [
    'jungundnaiv',
    'Jung & Naiv',
    'de',
    'Tilo Jung',
    'Long political interviews in German.',
    'interview,politics,longform',
    'current-affairs,ideas',
    'DE',
  ],
  [
    'maischberger',
    'maischberger',
    'de',
    'Sandra Maischberger',
    'German talk hour.',
    'interview,politics,public-media',
    'current-affairs,culture',
    'DE',
  ],
  [
    'franceculture',
    'France Culture',
    'fr',
    'France Culture',
    'Radio parlée : émissions longues.',
    'public-radio,interview,ideas',
    'ideas,culture',
    'FR',
  ],
  [
    'franceinter',
    'France Inter',
    'fr',
    'France Inter',
    'Grandes interviews.',
    'public-radio,interview,news',
    'news,culture',
    'FR',
  ],
  [
    'artdocumentary',
    'ARTE',
    'fr',
    'ARTE',
    'Documentaires et entretiens franco-allemands.',
    'documentary,public-media,interview',
    'documentary,culture',
    'FR',
  ],
  [
    'blast_fr',
    'Blast',
    'fr',
    'Denis Robert',
    'Média indépendant : entretiens longs.',
    'journalism,interview,politics',
    'news,current-affairs',
    'FR',
  ],
  [
    'thinkerview',
    'Thinkerview',
    'fr',
    'Thinkerview',
    'Interviews longues, plan fixe.',
    'interview,ideas,longform,politics',
    'ideas,current-affairs',
    'FR',
  ],
  [
    'konbini',
    'Konbini',
    'fr',
    'Konbini',
    'Longer French culture interviews (when not short-form).',
    'interview,culture',
    'culture,society-culture',
    'FR',
  ],
  [
    'fanpageit',
    'fanpage.it',
    'it',
    'fanpage.it',
    'Inchieste e interviste.',
    'journalism,interview,news',
    'news,journalism',
    'IT',
  ],
  [
    'repubblica',
    'la Repubblica',
    'it',
    'la Repubblica',
    'Interviste e reportage.',
    'news,interview,journalism',
    'news,current-affairs',
    'IT',
  ],
  [
    'corriere',
    'Corriere della Sera',
    'it',
    'Corriere',
    'Conversazioni lunghe.',
    'news,interview,journalism',
    'news,current-affairs',
    'IT',
  ],
  [
    'ilpost',
    'Il Post',
    'it',
    'Il Post',
    'Podcast e interviste in video.',
    'news,interview,explainer',
    'news,ideas',
    'IT',
  ],
  [
    'rtp',
    'RTP',
    'pt',
    'RTP',
    'Serviço público português: entrevistas.',
    'public-media,interview,news',
    'news,culture',
    'PT',
  ],
  [
    'expressopt',
    'Expresso',
    'pt',
    'Expresso',
    'Conversas do semanário.',
    'news,interview,journalism',
    'news,current-affairs',
    'PT',
  ],
  [
    'nosjournaal',
    'NOS',
    'nl',
    'NOS',
    'Dutch public news interviews.',
    'public-media,news,interview',
    'news,current-affairs',
    'NL',
  ],
  [
    'vpro',
    'VPRO',
    'nl',
    'VPRO',
    'Dutch long documentary and talk.',
    'documentary,public-media,interview',
    'documentary,culture',
    'NL',
  ],
  [
    'svt',
    'SVT',
    'sv',
    'SVT',
    'Swedish public-service talk.',
    'public-media,interview,news',
    'news,culture',
    'SE',
  ],
  [
    'drdk',
    'DR',
    'da',
    'DR',
    'Danish public-service interviews.',
    'public-media,interview,news',
    'news,culture',
    'DK',
  ],
  [
    'tvpinfo',
    'TVP Info',
    'pl',
    'TVP',
    'Polish public talk (treat as one desk among many).',
    'news,interview,public-media',
    'news,current-affairs',
    'PL',
  ],
  [
    'tvn24',
    'TVN24',
    'pl',
    'TVN24',
    'Polish news interviews.',
    'news,interview',
    'news,current-affairs',
    'PL',
  ],
  [
    'gazetapl',
    'Gazeta.pl',
    'pl',
    'Gazeta.pl',
    'Rozmowy i reportaże.',
    'news,interview,journalism',
    'news,journalism',
    'PL',
  ],
  [
    'theprintindia',
    'ThePrint',
    'en',
    'ThePrint',
    'Indian political interviews and Newstrack.',
    'news,interview,india,longform',
    'news,current-affairs',
    'IN',
  ],
  [
    'TheWireHindi',
    'The Wire Hindi',
    'hi',
    'The Wire',
    'हिंदी में साक्षात्कार और रिपोर्ट.',
    'news,interview,hindi,journalism',
    'news,current-affairs',
    'IN',
  ],
  [
    'scrollin',
    'Scroll.in',
    'en',
    'Scroll.in',
    'Indian explainers and interviews.',
    'news,interview,india,journalism',
    'news,journalism',
    'IN',
  ],
  [
    'newslaundry',
    'Newslaundry',
    'en',
    'Newslaundry',
    'Media-criticism conversations from India.',
    'news,media,interview,india',
    'news,current-affairs',
    'IN',
  ],
  [
    'thequint',
    'The Quint',
    'en',
    'The Quint',
    'Indian interviews and reports.',
    'news,interview,india',
    'news,current-affairs',
    'IN',
  ],
  [
    'ndtv',
    'NDTV',
    'en',
    'NDTV',
    'Indian news interviews.',
    'news,interview,india',
    'news,current-affairs',
    'IN',
  ],
  [
    'IndiaToday',
    'India Today',
    'en',
    'India Today',
    'To The Point and other interview hours.',
    'news,interview,india',
    'news,current-affairs',
    'IN',
  ],
  [
    'bbcnewsindia',
    'BBC News India',
    'en',
    'BBC',
    'Indian and South Asian interviews.',
    'news,interview,india',
    'news,current-affairs',
    'IN',
  ],
  [
    'abpnews',
    'ABP News',
    'hi',
    'ABP',
    'हिंदी बहस और साक्षात्कार.',
    'news,interview,hindi',
    'news,current-affairs',
    'IN',
  ],
  [
    'aajtak',
    'Aaj Tak',
    'hi',
    'Aaj Tak',
    'हिंदी समाचार और बातचीत.',
    'news,interview,hindi',
    'news,current-affairs',
    'IN',
  ],
  [
    'tv9bharatvarsh',
    'TV9 Bharatvarsh',
    'hi',
    'TV9',
    'हिंदी चर्चा.',
    'news,interview,hindi',
    'news,current-affairs',
    'IN',
  ],
  [
    'sochbymohak',
    'Soch by Mohak',
    'hi',
    'Mohak Mangal',
    'लंबे हिंदी व्याख्याता.',
    'explainer,education,hindi,longform',
    'education,ideas',
    'IN',
  ],
  [
    'dhruvrathee',
    'Dhruv Rathee',
    'hi',
    'Dhruv Rathee',
    'हिंदी राजनीतिक व्याख्या (लंबी).',
    'politics,explainer,hindi,longform',
    'current-affairs,education',
    'IN',
  ],
  [
    'thedeshbhaktlive',
    'The Deshbhakt Live',
    'hi',
    'Akash Banerjee',
    'लंबी हिंदी बातचीत.',
    'politics,satire,hindi,longform',
    'current-affairs,culture',
    'IN',
  ],
  [
    'nhkworldtv',
    'NHK WORLD-JAPAN',
    'en',
    'NHK',
    'English desk of Japanese public media.',
    'public-media,news,documentary',
    'news,documentary',
    'JP',
  ],
  [
    'nhk',
    'NHK',
    'ja',
    'NHK',
    '日本の公共放送：ドキュメンタリーと対談.',
    'public-media,documentary,interview',
    'news,culture',
    'JP',
  ],
  [
    'annnewsCH',
    'ANNnewsCH',
    'ja',
    'ANN',
    '報道と記者会見.',
    'news,interview',
    'news,current-affairs',
    'JP',
  ],
  [
    'tbsnews',
    'TBS NEWS DIG',
    'ja',
    'TBS',
    '報道番組.',
    'news,interview',
    'news,current-affairs',
    'JP',
  ],
  [
    'koreabroadcast',
    'KBS World TV',
    'en',
    'KBS',
    'Korean public media in English.',
    'public-media,news,culture',
    'news,culture',
    'KR',
  ],
  [
    'sbsnews',
    'SBS 뉴스',
    'ko',
    'SBS',
    '한국 시사 대담.',
    'news,interview',
    'news,current-affairs',
    'KR',
  ],
  [
    'jtbcnews',
    'JTBC News',
    'ko',
    'JTBC',
    '뉴스룸 인터뷰.',
    'news,interview',
    'news,current-affairs',
    'KR',
  ],
  [
    'thechinaexplained',
    'China Talk',
    'en',
    'Jordan Schneider',
    'Long China-policy interviews.',
    'interview,geopolitics,longform',
    'current-affairs,ideas',
    'US',
  ],
  [
    'sinicapodcast',
    'Sinica',
    'en',
    'Kaiser Kuo',
    'China conversations.',
    'interview,geopolitics,longform',
    'current-affairs,ideas',
    'US',
  ],
  [
    'scmp',
    'South China Morning Post',
    'en',
    'SCMP',
    'Hong Kong interviews and reports.',
    'news,interview,journalism',
    'news,current-affairs',
    'HK',
  ],
  [
    'channelnewsasia',
    'CNA',
    'en',
    'CNA',
    'Singapore interviews and Talk to Al Jazeera peers in SEA.',
    'news,interview,southeast-asia',
    'news,current-affairs',
    'SG',
  ],
  [
    'rappler',
    'Rappler',
    'en',
    'Rappler',
    'Philippine interviews and investigations.',
    'news,interview,journalism',
    'news,journalism',
    'PH',
  ],
  [
    'abs-cbnnews',
    'ABS-CBN News',
    'en',
    'ABS-CBN',
    'Philippine news interviews.',
    'news,interview',
    'news,current-affairs',
    'PH',
  ],
  [
    'kompascom',
    'Kompas.com',
    'id',
    'Kompas',
    'Wawancara dan laporan Indonesia.',
    'news,interview,journalism',
    'news,current-affairs',
    'ID',
  ],
  [
    'narasi',
    'Narasi',
    'id',
    'Najwa Shihab',
    'Mata Najwa and long Indonesian interviews.',
    'interview,news,longform',
    'news,current-affairs',
    'ID',
  ],
  [
    'mojokdotco',
    'Mojok',
    'id',
    'Mojok',
    'Esai dan obrolan Indonesia.',
    'culture,essay,interview',
    'culture,ideas',
    'ID',
  ],
  [
    'vtv24',
    'VTV24',
    'vi',
    'VTV',
    'Talk shows thời sự Việt Nam.',
    'news,interview,public-media',
    'news,current-affairs',
    'VN',
  ],
  [
    'bbcnewsafrique',
    'BBC Afrique',
    'fr',
    'BBC Afrique',
    'Émissions en français d’Afrique.',
    'news,interview,africa',
    'news,current-affairs',
    'GB',
  ],
  [
    'bbcnewspidgin',
    'BBC News Pidgin',
    'en',
    'BBC Pidgin',
    'West African pidgin news conversations.',
    'news,interview,west-africa',
    'news,culture',
    'NG',
  ],
  [
    'channelstv',
    'Channels Television',
    'en',
    'Channels TV',
    'Nigerian interview hours.',
    'news,interview,west-africa',
    'news,current-affairs',
    'NG',
  ],
  [
    'ariseentertainment247',
    'Arise News',
    'en',
    'Arise',
    'Nigerian and African interviews.',
    'news,interview,africa',
    'news,current-affairs',
    'NG',
  ],
  [
    'newzroomafrica',
    'Newzroom Afrika',
    'en',
    'Newzroom Afrika',
    'South African news interviews.',
    'news,interview,southern-africa',
    'news,current-affairs',
    'ZA',
  ],
  [
    'enca',
    'eNCA',
    'en',
    'eNCA',
    'South African interview desk.',
    'news,interview,southern-africa',
    'news,current-affairs',
    'ZA',
  ],
  [
    'dailymaverick',
    'Daily Maverick',
    'en',
    'Daily Maverick',
    'South African investigations and talks.',
    'journalism,interview,southern-africa',
    'news,journalism',
    'ZA',
  ],
  [
    'amabhungane',
    'amaBhungane',
    'en',
    'amaBhungane',
    'Investigative briefings.',
    'journalism,investigation,southern-africa',
    'journalism,news',
    'ZA',
  ],
  [
    'ntvkenya',
    'NTV Kenya',
    'en',
    'NTV Kenya',
    'Kenyan interviews.',
    'news,interview,east-africa',
    'news,current-affairs',
    'KE',
  ],
  [
    'citizentvkenya',
    'Citizen TV Kenya',
    'en',
    'Citizen TV',
    'Kenyan talk and news.',
    'news,interview,east-africa',
    'news,current-affairs',
    'KE',
  ],
  [
    'ajplus',
    'AJ+',
    'en',
    'AJ+',
    'Documentary shorts and some longer reports.',
    'documentary,news,global-south',
    'news,documentary',
    'QA',
  ],
  [
    'aljazeeraarabic',
    'الجزيرة',
    'ar',
    'Al Jazeera',
    'حوارات وبرامج طويلة بالعربية.',
    'news,interview,arabic,documentary',
    'news,current-affairs',
    'QA',
  ],
  [
    'bbcnewsarabic',
    'BBC News عربي',
    'ar',
    'BBC Arabic',
    'برامج وحوارات.',
    'news,interview,arabic',
    'news,current-affairs',
    'GB',
  ],
  [
    'alarabiya',
    'العربية',
    'ar',
    'Al Arabiya',
    'حوارات إخبارية.',
    'news,interview,arabic',
    'news,current-affairs',
    'AE',
  ],
  [
    'skynewsarabia',
    'سكاي نيوز عربية',
    'ar',
    'Sky News Arabia',
    'برامج حوارية.',
    'news,interview,arabic',
    'news,current-affairs',
    'AE',
  ],
  [
    'trtarabi',
    'TRT عربي',
    'ar',
    'TRT Arabic',
    'برامج وحوارات.',
    'news,interview,arabic',
    'news,current-affairs',
    'TR',
  ],
  [
    'maspero',
    'ماسبيرو',
    'ar',
    'Nile TV',
    'إعلام مصري رسمي: برامج.',
    'news,interview,arabic,public-media',
    'news,culture',
    'EG',
  ],
  [
    'kan11',
    'כאן 11 - חדשות',
    'he',
    'Kan',
    'ראיונות חדשותיים.',
    'news,interview,hebrew,public-media',
    'news,current-affairs',
    'IL',
  ],
  [
    'trtworlddigital',
    'TRT World Digital',
    'en',
    'TRT World',
    'Longer digital interviews.',
    'news,interview,documentary',
    'news,current-affairs',
    'TR',
  ],
];

function merge(existing: Channel[], extra: Channel[]): Channel[] {
  const byId = new Map<string, Channel>();
  const handles = new Set<string>();
  for (const channel of [...existing, ...extra]) {
    const handle = channel.handle.toLowerCase();
    if (handles.has(handle) || byId.has(channel.id)) continue;
    handles.add(handle);
    byId.set(channel.id, channel);
  }
  return [...byId.values()];
}

function main() {
  const file = path.join(
    process.cwd(),
    'data',
    'sources',
    'youtube-channels.json',
  );
  const existing = JSON.parse(readFileSync(file, 'utf8')) as Channel[];
  const merged = merge(existing, expand(PACK));
  writeFileSync(file, `${JSON.stringify(merged, null, 2)}\n`);
  const languages = new Set(merged.map((item) => item.language));
  const en = merged.filter((item) => item.language === 'en').length;
  const es = merged.filter((item) => item.language === 'es').length;
  console.log(
    `Wrote ${merged.length} YouTube channels (${en} en · ${es} es · ${languages.size} languages).`,
  );
}

main();
